export {
  multipleChoiceInputSchema,
  scaleInputSchema,
  subjectiveInputSchema,
  eitherOrInputSchema,
  tagInputSchema,
  ratingInputSchema,
  imageInputSchema,
  actionUpdateSchema,
  type MultipleChoiceInput,
  type ScaleInput,
  type SubjectiveInput,
  type EitherOrInput,
  type TagInput,
  type RatingInput,
  type ImageInput,
  type ActionUpdate,
} from "./actionSchema";
