export {
  multipleChoiceInputSchema,
  scaleInputSchema,
  subjectiveInputSchema,
  eitherOrInputSchema,
  tagInputSchema,
  ratingInputSchema,
  imageInputSchema,
  questionUpdateSchema,
  type MultipleChoiceInput,
  type ScaleInput,
  type SubjectiveInput,
  type EitherOrInput,
  type TagInput,
  type RatingInput,
  type ImageInput,
  type QuestionUpdate,
} from "./actionSchema";
