import type { Metadata } from "next";
import "./globals.css";
import { QueryProvider } from "@/components/providers/QueryProvider";
import { Suspense } from "react";
import { BottomCTALayout } from "@repo/ui/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <link
          href="https://cdn.jsdelivr.net/gh/sun-typeface/SUIT@2/fonts/variable/woff2/SUIT-Variable.css"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased">
        <BottomCTALayout className="max-w-lg min-h-screen mx-auto">
          <QueryProvider>
            <Suspense
              fallback={
                <div className="grid min-h-[100svh] place-items-center">
                  <div className="text-sm text-[--color-muted-foreground]">
                    로딩 중...
                  </div>
                </div>
              }
            >
              {children}
            </Suspense>
          </QueryProvider>
        </BottomCTALayout>
      </body>
    </html>
  );
}
