import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { QueryProvider } from "@/components/providers/QueryProvider";
import { AuthGate } from "@/components/providers/AuthGate";
import { Suspense } from "react";
import "./globals.css";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <QueryProvider>
          <Suspense fallback={<div className="grid min-h-[100svh] place-items-center"><div className="text-sm text-[--color-muted-foreground]">로딩 중...</div></div>}>
            <AuthGate>{children}</AuthGate>
          </Suspense>
        </QueryProvider>
      </body>
    </html>
  );
}
